keys:
  - &laptop age1gefpgtfu0hjw69yjy6uvxtjn7nv97mrdx854ahmyzefkgsm05gasx8zjz8
  - &netcup age1z867ql2cecqd46h46xd035zhsafnp90fffzre4ge9ec7lqedvpcsrayxl8
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *laptop
      - *netcup
